name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          import-map: ./import_map.json
          project: dust # the name of the project on Deno Deploy
          entrypoint: server.ts # the entrypoint to deploy